[email]
email = ""
password = ""
server = ""
mailbox = ""
sleep_time = 60
ffnet_disable = true

[calibre]
path=""
username=""
password=""
default_ini=""
personal_ini=""
update_method="update"

[pushbullet]
enabled = false
api_key = ""
device = ""

[apprise]
# List of Apprise URLs to send notifications to.
# For example:
# urls = [
#   "pbul://PUSHBULLET_API_KEY",  # For Pushbullet
#   "discord://WEBHOOK_ID/WEBHOOK_TOKEN", # For Discord
#   "mailto://USER:PASSWORD@HOST:PORT", # For Email
# ]
urls = []